import time

import rclpy

from rclpy.node import Node
from rclpy.qos import QoSProfile
from rclpy.qos import ReliabilityPolicy
from rclpy.qos import DurabilityPolicy

from sensor_msgs.msg import Joy

from std_msgs.msg import Bool
from std_msgs.msg import String

from dobot_e6_msgs.msg import JointVelocityCommand


class DobotE6Joystick(Node):

    def __init__(self):

        super().__init__('dobot_e6_joystick')

        # ============================================================
        # Parameters
        # ============================================================

        # ------------------------------------------------------------
        # General control
        # ------------------------------------------------------------

        self.declare_parameter(
            'publish_frequency_hz',
            30.0
        )

        self.declare_parameter(
            'joy_timeout_s',
            0.25
        )

        self.declare_parameter(
            'deadzone',
            0.08
        )

        # ------------------------------------------------------------
        # Velocity configuration
        # ------------------------------------------------------------

        # Maximum velocity generated by analog sticks [rad/s]
        self.declare_parameter(
            'analog_max_velocity_rad_s',
            1.0
        )

        # Constant velocity generated by digital buttons [rad/s]
        self.declare_parameter(
            'button_velocity_rad_s',
            0.5
        )

        # ------------------------------------------------------------
        # Analog axis mapping
        # ------------------------------------------------------------

        # Left stick vertical -> Joint 1
        self.declare_parameter(
            'axis_joint1',
            1
        )

        # Left stick horizontal -> Joint 2
        self.declare_parameter(
            'axis_joint2',
            0
        )

        # Right stick vertical -> Joint 3
        self.declare_parameter(
            'axis_joint3',
            4
        )

        # Right stick horizontal -> Joint 4
        self.declare_parameter(
            'axis_joint4',
            3
        )

        # ------------------------------------------------------------
        # Analog axis directions
        # ------------------------------------------------------------

        self.declare_parameter(
            'axis_joint1_sign',
            1.0
        )

        self.declare_parameter(
            'axis_joint2_sign',
            1.0
        )

        self.declare_parameter(
            'axis_joint3_sign',
            1.0
        )

        self.declare_parameter(
            'axis_joint4_sign',
            1.0
        )

        # ------------------------------------------------------------
        # Button mapping
        # ------------------------------------------------------------

        # Arrow UP -> Joint 5
        self.declare_parameter(
            'button_joint5',
            -1
        )

        # Arrow DOWN -> Joint 6
        self.declare_parameter(
            'button_joint6',
            -1
        )

        # Y -> suction toggle
        self.declare_parameter(
            'button_suction',
            -1
        )

        # X -> stop all joint motion
        self.declare_parameter(
            'button_stop',
            -1
        )

        # ------------------------------------------------------------
        # Button directions
        # ------------------------------------------------------------

        self.declare_parameter(
            'joint5_button_sign',
            1.0
        )

        self.declare_parameter(
            'joint6_button_sign',
            1.0
        )

        # ============================================================
        # Read parameters
        # ============================================================

        self.publish_frequency_hz = float(
            self.get_parameter(
                'publish_frequency_hz'
            ).value
        )

        self.joy_timeout_s = float(
            self.get_parameter(
                'joy_timeout_s'
            ).value
        )

        self.deadzone = float(
            self.get_parameter(
                'deadzone'
            ).value
        )

        self.analog_max_velocity_rad_s = float(
            self.get_parameter(
                'analog_max_velocity_rad_s'
            ).value
        )

        self.button_velocity_rad_s = float(
            self.get_parameter(
                'button_velocity_rad_s'
            ).value
        )

        self.axis_joint1 = int(
            self.get_parameter(
                'axis_joint1'
            ).value
        )

        self.axis_joint2 = int(
            self.get_parameter(
                'axis_joint2'
            ).value
        )

        self.axis_joint3 = int(
            self.get_parameter(
                'axis_joint3'
            ).value
        )

        self.axis_joint4 = int(
            self.get_parameter(
                'axis_joint4'
            ).value
        )

        self.axis_joint1_sign = float(
            self.get_parameter(
                'axis_joint1_sign'
            ).value
        )

        self.axis_joint2_sign = float(
            self.get_parameter(
                'axis_joint2_sign'
            ).value
        )

        self.axis_joint3_sign = float(
            self.get_parameter(
                'axis_joint3_sign'
            ).value
        )

        self.axis_joint4_sign = float(
            self.get_parameter(
                'axis_joint4_sign'
            ).value
        )

        self.button_joint5 = int(
            self.get_parameter(
                'button_joint5'
            ).value
        )

        self.button_joint6 = int(
            self.get_parameter(
                'button_joint6'
            ).value
        )

        self.button_suction = int(
            self.get_parameter(
                'button_suction'
            ).value
        )

        self.button_stop = int(
            self.get_parameter(
                'button_stop'
            ).value
        )

        self.joint5_button_sign = float(
            self.get_parameter(
                'joint5_button_sign'
            ).value
        )

        self.joint6_button_sign = float(
            self.get_parameter(
                'joint6_button_sign'
            ).value
        )

        # ============================================================
        # Parameter validation
        # ============================================================

        if self.publish_frequency_hz <= 0.0:

            raise ValueError(
                'publish_frequency_hz must be greater than zero.'
            )

        if self.joy_timeout_s <= 0.0:

            raise ValueError(
                'joy_timeout_s must be greater than zero.'
            )

        if (
            self.deadzone < 0.0
            or self.deadzone >= 1.0
        ):

            raise ValueError(
                'deadzone must be in the range [0.0, 1.0).'
            )

        if (
            self.analog_max_velocity_rad_s <= 0.0
            or self.analog_max_velocity_rad_s > 1.0
        ):

            raise ValueError(
                'analog_max_velocity_rad_s must be '
                'greater than 0 and <= 1.0 rad/s.'
            )

        if (
            self.button_velocity_rad_s <= 0.0
            or self.button_velocity_rad_s > 1.0
        ):

            raise ValueError(
                'button_velocity_rad_s must be '
                'greater than 0 and <= 1.0 rad/s.'
            )

        # ============================================================
        # Internal state
        # ============================================================

        self.latest_joy = None

        self.last_joy_time = None

        self.velocity_active = False

        self.control_mode = 'UNKNOWN'

        self.suction_active = False

        self.suction_state_valid = False

        self.previous_suction_button = False

        self.previous_stop_button = False

        # ============================================================
        # QoS
        # ============================================================

        monitor_qos = QoSProfile(
            depth=1,
            reliability=ReliabilityPolicy.RELIABLE,
            durability=DurabilityPolicy.TRANSIENT_LOCAL
        )

        # ============================================================
        # Publishers
        # ============================================================

        self.velocity_publisher = self.create_publisher(
            JointVelocityCommand,
            '/dobot/joint_velocity_cmd',
            10
        )

        self.suction_publisher = self.create_publisher(
            Bool,
            '/dobot/suction_gripper',
            10
        )

        # ============================================================
        # Subscribers
        # ============================================================

        self.joy_subscriber = self.create_subscription(
            Joy,
            '/joy',
            self.joy_callback,
            10
        )

        self.control_mode_subscriber = self.create_subscription(
            String,
            '/dobot/control_mode_monitor',
            self.control_mode_callback,
            monitor_qos
        )

        self.suction_monitor_subscriber = self.create_subscription(
            Bool,
            '/dobot/suction_gripper_monitor',
            self.suction_monitor_callback,
            10
        )

        # ============================================================
        # Control timer
        # ============================================================

        control_period = (
            1.0 / self.publish_frequency_hz
        )

        self.control_timer = self.create_timer(
            control_period,
            self.control_loop
        )

        # ============================================================
        # Startup information
        # ============================================================

        self.get_logger().info(
            '\n'
            '============================================================\n'
            ' DOBOT MAGICIAN E6 - JOYSTICK CONTROL\n'
            '============================================================\n'
            ' Left stick UP / DOWN      -> Joint 1\n'
            ' Left stick LEFT / RIGHT   -> Joint 2\n'
            ' Right stick UP / DOWN     -> Joint 3\n'
            ' Right stick LEFT / RIGHT  -> Joint 4\n'
            ' Arrow UP                  -> Joint 5\n'
            ' Arrow DOWN                -> Joint 6\n'
            ' Y                         -> Suction ON / OFF\n'
            ' X                         -> STOP joint motion\n'
            '------------------------------------------------------------\n'
            f' Analog max velocity       : '
            f'{self.analog_max_velocity_rad_s:.2f} rad/s\n'
            f' Button velocity           : '
            f'{self.button_velocity_rad_s:.2f} rad/s\n'
            f' Deadzone                  : '
            f'{self.deadzone:.2f}\n'
            '============================================================'
        )

    # ================================================================
    # Joy callback
    # ================================================================

    def joy_callback(self, msg):

        self.latest_joy = msg

        self.last_joy_time = time.monotonic()

        # ------------------------------------------------------------
        # Suction gripper toggle
        # ------------------------------------------------------------

        suction_button = self.get_button(
            msg,
            self.button_suction
        )

        # Rising edge only
        if (
            suction_button
            and not self.previous_suction_button
        ):

            self.toggle_suction()

        self.previous_suction_button = (
            suction_button
        )

    # ================================================================
    # Control mode callback
    # ================================================================

    def control_mode_callback(self, msg):

        self.control_mode = msg.data

    # ================================================================
    # Suction monitor callback
    # ================================================================

    def suction_monitor_callback(self, msg):

        self.suction_active = bool(
            msg.data
        )

        self.suction_state_valid = True

    # ================================================================
    # Toggle suction
    # ================================================================

    def toggle_suction(self):

        new_state = not self.suction_active

        msg = Bool()

        msg.data = new_state

        self.suction_publisher.publish(
            msg
        )

        # Update locally immediately.
        # The driver monitor will later confirm the real Tool DO state.

        self.suction_active = new_state

        if new_state:

            self.get_logger().info(
                'Suction gripper command: ON'
            )

        else:

            self.get_logger().info(
                'Suction gripper command: OFF'
            )

    # ================================================================
    # Main control loop
    # ================================================================

    def control_loop(self):

        # ------------------------------------------------------------
        # Wait until the first joystick message
        # ------------------------------------------------------------

        if self.latest_joy is None:

            return

        if self.last_joy_time is None:

            return

        # ============================================================
        # Joystick watchdog
        # ============================================================

        joy_age = (
            time.monotonic()
            - self.last_joy_time
        )

        if joy_age > self.joy_timeout_s:

            if self.velocity_active:

                self.publish_zero_velocity()

                self.velocity_active = False

                self.get_logger().warning(
                    'Joystick timeout. '
                    'Joint velocity command stopped.'
                )

            return

        joy = self.latest_joy

        # ============================================================
        # STOP BUTTON
        #
        # X has priority over all motion controls.
        # ============================================================

        stop_button = self.get_button(
            joy,
            self.button_stop
        )

        if stop_button:

            # Send the stop command only on the rising edge.
            if not self.previous_stop_button:

                self.publish_zero_velocity()

                self.get_logger().warning(
                    'Joystick STOP pressed. '
                    'All commanded joint velocities set to zero.'
                )

            self.previous_stop_button = True

            self.velocity_active = False

            return

        self.previous_stop_button = False

        # ============================================================
        # Control mode validation
        # ============================================================

        # Joystick velocity control is allowed only when the driver
        # is IDLE or already in VELOCITY mode.

        if self.control_mode not in (
            'IDLE',
            'VELOCITY'
        ):

            return

        # ============================================================
        # Joint 1
        #
        # Left stick UP / DOWN
        # ============================================================

        joint1_input = self.get_axis(
            joy,
            self.axis_joint1
        )

        joint1_input = self.apply_deadzone(
            joint1_input
        )

        joint1_velocity = (
            self.axis_joint1_sign
            * joint1_input
            * self.analog_max_velocity_rad_s
        )

        # ============================================================
        # Joint 2
        #
        # Left stick LEFT / RIGHT
        # ============================================================

        joint2_input = self.get_axis(
            joy,
            self.axis_joint2
        )

        joint2_input = self.apply_deadzone(
            joint2_input
        )

        joint2_velocity = (
            self.axis_joint2_sign
            * joint2_input
            * self.analog_max_velocity_rad_s
        )

        # ============================================================
        # Joint 3
        #
        # Right stick UP / DOWN
        # ============================================================

        joint3_input = self.get_axis(
            joy,
            self.axis_joint3
        )

        joint3_input = self.apply_deadzone(
            joint3_input
        )

        joint3_velocity = (
            self.axis_joint3_sign
            * joint3_input
            * self.analog_max_velocity_rad_s
        )

        # ============================================================
        # Joint 4
        #
        # Right stick LEFT / RIGHT
        # ============================================================

        joint4_input = self.get_axis(
            joy,
            self.axis_joint4
        )

        joint4_input = self.apply_deadzone(
            joint4_input
        )

        joint4_velocity = (
            self.axis_joint4_sign
            * joint4_input
            * self.analog_max_velocity_rad_s
        )

        # ============================================================
        # Joint 5
        #
        # Arrow UP
        # Constant velocity while button is held.
        # ============================================================

        if self.get_button(
            joy,
            self.button_joint5
        ):

            joint5_velocity = (
                self.joint5_button_sign
                * self.button_velocity_rad_s
            )

        else:

            joint5_velocity = 0.0

        # ============================================================
        # Joint 6
        #
        # Arrow DOWN
        # Constant velocity while button is held.
        # ============================================================

        if self.get_button(
            joy,
            self.button_joint6
        ):

            joint6_velocity = (
                self.joint6_button_sign
                * self.button_velocity_rad_s
            )

        else:

            joint6_velocity = 0.0

        # ============================================================
        # Complete desired joint velocity vector
        # ============================================================

        velocity = [
            joint1_velocity,
            joint2_velocity,
            joint3_velocity,
            joint4_velocity,
            joint5_velocity,
            joint6_velocity,
        ]

        motion_requested = any(
            abs(value) > 1e-6
            for value in velocity
        )

        # ============================================================
        # Publish active motion
        # ============================================================

        if motion_requested:

            self.publish_velocity(
                velocity
            )

            self.velocity_active = True

            return

        # ============================================================
        # Controls returned to neutral
        # ============================================================

        # Send exactly one zero velocity command when all sticks
        # and motion buttons return to neutral.

        if self.velocity_active:

            self.publish_zero_velocity()

            self.velocity_active = False

    # ================================================================
    # Publish velocity
    # ================================================================

    def publish_velocity(self, velocity):

        msg = JointVelocityCommand()

        msg.velocity = [
            float(value)
            for value in velocity
        ]

        self.velocity_publisher.publish(
            msg
        )

    # ================================================================
    # Publish zero velocity
    # ================================================================

    def publish_zero_velocity(self):

        msg = JointVelocityCommand()

        msg.velocity = [
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
            0.0,
        ]

        self.velocity_publisher.publish(
            msg
        )

    # ================================================================
    # Safe axis access
    # ================================================================

    @staticmethod
    def get_axis(msg, index):

        if index < 0:

            return 0.0

        if index >= len(msg.axes):

            return 0.0

        return float(
            msg.axes[index]
        )

    # ================================================================
    # Safe button access
    # ================================================================

    @staticmethod
    def get_button(msg, index):

        if index < 0:

            return False

        if index >= len(msg.buttons):

            return False

        return bool(
            msg.buttons[index]
        )

    # ================================================================
    # Analog deadzone
    # ================================================================

    def apply_deadzone(self, value):

        # Clamp the raw joystick signal to its expected range.

        value = max(
            -1.0,
            min(
                1.0,
                float(value)
            )
        )

        magnitude = abs(
            value
        )

        # ------------------------------------------------------------
        # Inside deadzone
        # ------------------------------------------------------------

        if magnitude <= self.deadzone:

            return 0.0

        # ------------------------------------------------------------
        # Remove deadzone and rescale remaining range
        # ------------------------------------------------------------

        scaled_magnitude = (
            magnitude - self.deadzone
        ) / (
            1.0 - self.deadzone
        )

        if value < 0.0:

            return -scaled_magnitude

        return scaled_magnitude


def main(args=None):

    rclpy.init(
        args=args
    )

    node = DobotE6Joystick()

    try:

        rclpy.spin(
            node
        )

    except KeyboardInterrupt:

        pass

    finally:

        # If the joystick controller is closed while actively
        # commanding motion, send one final zero velocity command.

        if node.velocity_active:

            node.publish_zero_velocity()

        node.destroy_node()

        rclpy.shutdown()


if __name__ == '__main__':

    main()